content = open("create_sig_apis.py", "rb").read()
content = content.replace(b"\x97", b"-")
content = content.replace(b"\xed", b"i")
content = content.replace(b"\xe9", b"e")
content = content.replace(b"\xf3", b"o")
content = content.replace(b"\xfa", b"u")
content = content.replace(b"\xe1", b"a")
open("create_sig_apis.py", "wb").write(content)
print("OK")
